# Generated by Django 3.1.2 on 2021-05-04 18:25

import core_features.utils
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('audiobook_id', models.AutoField(primary_key=True, serialize=False)),
                ('audiobook_title', models.CharField(max_length=100)),
                ('audiobook_author', models.CharField(max_length=100)),
                ('audiobook_narrator', models.CharField(max_length=100)),
                ('audiobook_duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, validators=[core_features.utils.check_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('podcast_id', models.AutoField(primary_key=True, serialize=False)),
                ('audiobook_name', models.CharField(max_length=100)),
                ('podcast_duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, validators=[core_features.utils.check_date])),
                ('audiobook_host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('song_duration', models.PositiveBigIntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True, validators=[core_features.utils.check_date])),
            ],
        ),
    ]
